
export const ACTIONS = {
    SET_POSITION_DETAILS:'SET_POSITION_DETAILS',
    SET_ERROR : 'SET_ERROR',
    SET_IS_SUCCESS : 'SET_IS_SUCCESS',
    SET_SEARCH_LIST : 'SET_SEARCH_LIST',
    SET_SAVED_LOCATIONS : 'SET_SAVED_LOCATIONS',
    SET_SEARCH_ADDRESS_POSITION : 'SET_SEARCH_ADDRESS_POSITION',

    // SET_POSITION_DETAILS:'SET_POSITION_DETAILS',
};


