
export const ACTIONS = {
    SET_MAP_TYPE:'SET_MAP_TYPE',
    SET_MAP_TRAFFIC : 'SET_MAP_TRAFFIC',
    SET_REGION_CHANGE : 'SET_REGION_CHANGE',
    SET_LOADER : 'SET_LOADER',
    SET_USER_CURRENT_POSITION : 'SET_USER_CURRENT_POSITION',
    SET_USER_TARGET_POSITION : 'SET_USER_TARGET_POSITION',
    SET_MAP_NEW_TARGET_POSITION : 'SET_MAP_NEW_TARGET_POSITION',
    SET_DOCTORS_NEAR_BY_ON_MAP : 'SET_DOCTORS_NEAR_BY_ON_MAP',
    SET_DOCTOR_INFO : 'SET_DOCTOR_INFO',
};


