

export const LOGIN_COMMANDS = {
    MAIN_PAGE:'MAIN_PAGE',
    PHONE_VERIFICATION:'PHONE_VERIFICATION',
    USER_INFO:'USER_INFO',
    REGISTRATION_PAGE:'REGISTRATION_PAGE',
    FACEBOOK:'FACEBOOK',
    PHONE: 'PHONE',
};

export const LOGIN_TYPES = {
    PHONE: 'PHONE',
    FACEBOOK: 'FACEBOOK'
};

export const ACTIONS = {
    IS_REQUEST_SUCCESS:'IS_REQUEST_SUCCESS'
};


