import Main from './main/main';
import Map from './map/map';
import Phone from './phone/phone';
import Verification from './verification/verification';
import UserInfo from './userInfo/userInfo';
import Location from './location/location';
import Orders from './orders/orders';
import Notifications from './notifications/notifications';
import Help from './help/help';
import Settings from './settings/settings';
import Username from './username/username';
import Email from './email/email';
import UpdatePassword from './updatePassword/updatePassword';
import Splash from './splash/splash';
import Facebook from './facebook/facebook';
import SignOut from './signout/signout';
import SaveLocation from './saveLocation/saveLocation';

export {Main};
export {Verification};
export {UserInfo};
export {Phone};
export {Map};
export {Location};
export {Orders};
export {Notifications};
export {Help};
export {Settings};
export {Username};
export {Email};
export {UpdatePassword};
export {Splash};
export {Facebook};
export {SignOut};
export {SaveLocation};